configName: S70_DT3
folderName: usb_host_msd_s70
format_version: v1.0
frameworkPath: ..\..\Harmony3
processor: ATSAMS70N19B
projectName: usb_host_msd_s70
settings:
  PackageFilter: audio;bootloader;bootloader_apps_uart;bsp;core;core_apps_sam_d21_da1;core_apps_sam_d5x_e5x;core_apps_sam_e70_s70_v70_v71;core_apps_sam_l22;crypto;cryptoauthlib;csp;csp_apps_sam_d11;csp_apps_sam_d21_da1;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_l22;Devices;dev_packs;gfx;gfx_apps;gfx_apps_sam_d5x_e5x;gfx_apps_sam_e70_s70_v70_v71;gfx_aria;harmony-services;MPLAB-Harmony-Reference-Apps;net;net_apps_sam_e5x;net_apps_sam_e70_v71;quick_docs;touch;usb;wireless_apps_winc1500;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMS70_DFP\4.6.82\sams70b\atdf\ATSAMS70N19B.atdf
